import { ObjectId } from "mongodb"

export interface Wallet {
  _id: ObjectId
  userId: string
  name: string
  type: "bank" | "cash" | "credit_card" | "savings" | "investment" | "lent"
  currency: string        // ISO 4217: "USD", "INR", "EUR"
  balance: number         // Store in smallest unit (cents / paise)
  color: string           // Hex color
  icon: string            // Icon name string
  isArchived: boolean
  createdAt: Date
  updatedAt: Date
  organizationId?: string | null
  ownerUserId?: string
  createdBy?: string
  updatedBy?: string
  version?: number
}

export interface Transaction {
  _id: ObjectId
  userId: string
  walletId: string
  categoryId?: string | null
  type: "income" | "expense" | "transfer"
  amount: number          // Always positive; type determines direction
  currency: string
  description: string
  notes?: string
  date: Date              // User-specified date, not createdAt
  tags: string[]
  isRecurring: boolean
  recurringId?: string    // Links to recurring_rules._id if generated by a rule
  linkedTransactionId?: string // Links two transaction records in a transfer
  transferType?: "debit" | "credit" // Determines if this transaction is the source (debit) or destination (credit) of a transfer
  goalId?: string         // Optional link to a Goal document for savings goals contributions
  budgetId?: string | null // Optional link to a Budget override
  isFlagged?: boolean
  needsReview?: boolean
  splitMode?: "amount" | "percentage" | "equal"
  splits?: { id: string; categoryId: string; amount: number; percentage?: number; notes?: string }[]
  loanId?: string
  isLoanPrincipal?: boolean
  isInvestment?: boolean
  investmentType?: string
  symbol?: string
  createdAt: Date
  updatedAt: Date
  organizationId?: string | null
  ownerUserId?: string
  createdBy?: string
  updatedBy?: string
  version?: number
}

export interface Category {
  _id: ObjectId
  userId: string | null   // null = system default (shared); string = user-owned
  name: string
  type: ("income" | "expense" | "transfer")[]
  icon: string
  color: string
  parentId?: string       // For subcategories
  isDefault: boolean
  createdAt: Date
  updatedAt?: Date
  organizationId?: string | null
  ownerUserId?: string
  createdBy?: string
  updatedBy?: string
  version?: number
}

export interface Budget {
  _id: ObjectId
  userId: string
  categoryId: string
  walletId?: string       // undefined = applies across all wallets
  name: string
  amount: number
  currency: string
  period: "daily" | "weekly" | "monthly" | "yearly"
  startDate: Date
  endDate?: Date
  isActive: boolean
  alertThreshold: number  // 0–100; alert when spending % hits this value
  createdAt: Date
  updatedAt: Date
  organizationId?: string | null
  ownerUserId?: string
  createdBy?: string
  updatedBy?: string
  version?: number
}

export interface BudgetTemplateAllocation {
  categoryName: string
  categoryId?: string
  group: "Needs" | "Wants" | "Savings" | "Custom"
  percentage: number // 0–100
  fixedAmount?: number // in cents/paise
  suggestedColor: string
  suggestedIcon: string
  alertThreshold: number // default 80
  description?: string
}

export interface BudgetTemplate {
  _id: ObjectId | string
  userId: string | null // null = system preset
  organizationId?: string | null
  name: string
  tagline: string
  description: string
  category: "framework" | "lifestyle" | "goals" | "custom"
  methodology: "percentage" | "fixed"
  icon: string
  color: string
  tags: string[]
  allocations: BudgetTemplateAllocation[]
  rulesSummary: string[]
  isSystem: boolean
  basedOnTemplateId?: string
  period: "daily" | "weekly" | "monthly" | "yearly"
  createdAt: Date
  updatedAt: Date
  ownerUserId?: string
  createdBy?: string
  updatedBy?: string
  version?: number
}

export interface TemplateRecommendation {
  recommendedTemplateId: string
  templateName: string
  rationale: string
  suggestedMonthlyAmount: number // in smallest currency unit (cents / paise)
  currency: string
  averageMonthlyIncome: number
  hasSufficientData: boolean
}

export interface RecurringRule {
  _id: ObjectId
  userId: string
  walletId: string
  categoryId: string
  type: "income" | "expense"
  amount: number
  currency: string
  description: string
  frequency: "daily" | "weekly" | "biweekly" | "monthly" | "quarterly" | "yearly"
  startDate: Date
  endDate?: Date
  nextDueDate: Date
  lastProcessedDate?: Date
  isActive: boolean
  tags: string[]
  createdAt: Date
  updatedAt: Date
  organizationId?: string | null
  ownerUserId?: string
  createdBy?: string
  updatedBy?: string
  version?: number
  
  // Subscription / Bill specific fields
  kind?: "recurring" | "subscription" | "bill"
  providerName?: string
  providerUrl?: string
  cancellationUrl?: string
  trialEndDate?: Date
  reminderDaysBefore?: number
  nextRenewalDate?: Date
  lastRenewalDate?: Date
  renewalPrice?: number
  cancelledAt?: Date
  cancelReason?: string
  status?: "active" | "trial" | "paused" | "cancelled" | "expired"
  lastReminderSentAt?: Date
}

export interface ExchangeRate {
  _id: ObjectId
  base: string
  rates: Record<string, number>
  updatedAt: Date
}

export interface User {
  id: string
  email: string
  name: string
  emailVerified: boolean
  image?: string
  createdAt: Date
  updatedAt: Date
  role: "admin" | "user"
  banned?: boolean
  banReason?: string
  banExpires?: Date
  twoFactorEnabled?: boolean
  approved: boolean
}

export interface Session {
  id: string
  userId: string
  expiresAt: Date
  token: string
  createdAt: Date
  updatedAt: Date
  ipAddress?: string
  userAgent?: string
  impersonatedBy?: string
}

export interface Goal {
  _id: ObjectId
  userId: string
  name: string
  targetAmount: number     // stored in lowest currency units (e.g. cents)
  currentAmount: number    // stored in lowest currency units
  currency: string         // ISO 4217 code
  targetDate: Date
  walletId?: string        // optional associated wallet
  color: string
  icon: string
  createdAt: Date
  updatedAt: Date
  organizationId?: string | null
  ownerUserId?: string
  createdBy?: string
  updatedBy?: string
  version?: number
}

export type SpaceType = "family" | "couple" | "business" | "travel" | "roommates" | "other";

export interface OrganizationSettings {
  _id: ObjectId;
  organizationId: string;
  baseCurrency: string;
  fiscalYearStartMonth: number;
  spaceType: SpaceType;
  updatedBy: string;
  updatedAt: Date;
  version: number;
}

export interface Notification {
  _id: ObjectId;
  userId: string;
  title: string;
  message: string;
  type: string;
  link?: string;
  image?: string;
  read?: boolean;
  readAt?: Date;
  dismissedAt?: Date;
  archivedAt?: Date;
  deletedAt?: Date;
  createdAt: Date;
  updatedAt: Date;
}

export interface SerializedNotification {
  _id: string;
  userId: string;
  title: string;
  message: string;
  type: string;
  link?: string | null;
  image?: string | null;
  readAt?: string | null;
  dismissedAt?: string | null;
  archivedAt?: string | null;
  deletedAt?: string | null;
  createdAt: string;
  updatedAt: string;
}


export type RuleTrigger = "manual" | "receipt" | "csv_import" | "recurring" | "api";

export type ExecutionMode = "all_matches" | "first_match";

export type ConditionField = "description" | "amount" | "walletId" | "walletType" | "currency" | "tags";

export type ConditionOperator = 
  | "contains" | "equals" | "starts_with" | "ends_with" | "regex"
  | "gt" | "lt" | "eq" | "gte" | "lte"
  | "contains_tag";

export type ConditionValue = string | number | boolean | string[];

export interface RuleCondition {
  field: ConditionField
  operator: ConditionOperator
  value: ConditionValue
}

export type RuleAction = 
  | { type: "assign_category"; categoryId: string }
  | { type: "assign_tags"; tags: string[] }
  | { type: "assign_budget"; budgetId: string }
  | { type: "set_notes"; notes: string }
  | { type: "mark_recurring"; isRecurring: boolean }
  | { type: "flag_transaction"; isFlagged: boolean; needsReview: boolean }
  | { type: "auto_split"; splits: { id?: string; categoryId: string; amount: number; notes?: string }[] }
  | { type: "move_to_wallet"; walletId: string };

export type RuleStatus = "draft" | "active" | "disabled";

export interface AutomationRule {
  _id: ObjectId
  userId: string
  organizationId: string | null
  name: string
  description?: string
  status: RuleStatus
  priority: number           // Higher executes first
  stopProcessing: boolean    // If true, stop subsequent evaluations if this rule matches
  triggers: RuleTrigger[]    // Contexts in which this rule applies
  conditions: RuleCondition[]
  conditionOperator: "and" | "or"
  actions: RuleAction[]
  
  // Statistics
  executionCount: number
  lastExecutedAt: Date | null
  lastMatchedAt: Date | null
  
  version: number
  createdAt: Date
  updatedAt: Date
  createdBy: string
  updatedBy: string
}

export interface RuleConflict {
  field: string
  winningRuleId: string
  winningRuleName: string
  losingRuleId: string
  losingRuleName: string
  valueAttempted: unknown
  valueApplied: unknown
}

export interface RuleExecutionResult {
  originalTransaction: Partial<Transaction>
  modifiedTransaction: Partial<Transaction>
  matchedRulesCount: number
  appliedRules: {
    ruleId: string
    ruleName: string
    actionsApplied: RuleAction[]
  }[]
  skippedRules: {
    ruleId: string
    ruleName: string
    reason: "stop_processing_triggered" | "trigger_mismatch" | "disabled" | "condition_mismatch"
  }[]
  conflicts: RuleConflict[]
  warnings: string[]
  stopProcessingTriggered: boolean
}

export interface AutomationJob {
  _id: ObjectId
  userId: string
  organizationId: string | null
  ruleId: string
  status: "pending" | "processing" | "completed" | "failed"
  totalTransactions: number
  processedTransactions: number
  matchedTransactions: number
  error?: string
  createdAt: Date
  updatedAt: Date
}

export interface Contact {
  _id: ObjectId
  userId: string
  organizationId: string | null
  name: string
  email?: string
  phone?: string
  notes?: string
  metadata?: Record<string, unknown>
  createdAt: Date
  updatedAt: Date
  version: number
}

export interface Loan {
  _id: ObjectId
  userId: string
  organizationId: string | null
  type: "lent" | "borrowed"
  contactId: string
  personName: string
  amount: number
  currency: string
  interestRate?: number
  walletId: string
  transactionId: string
  date: Date
  dueDate?: Date
  notes?: string
  status: "active" | "partially_repaid" | "fully_repaid" | "overdue" | "cancelled"
  remainingAmount: number
  reminderSchedule: number[]
  sentReminders: number[]
  lastOverdueReminderSentAt?: Date
  metadata?: Record<string, unknown>
  createdAt: Date
  updatedAt: Date
  version: number
}

export interface LoanRepayment {
  _id: ObjectId
  loanId: string
  transactionId: string
  amount: number
  date: Date
  notes?: string
  createdAt: Date
}

export interface OwedSummaries {
  totalLent: number
  totalBorrowed: number
  dueThisMonth: number
  overdue: number
  repaidThisMonth: number
  baseCurrency: string
}


export interface BillInstance {
  _id: ObjectId
  userId: string
  organizationId?: string | null
  ruleId: string // Reference to the RecurringRule template
  description: string
  expectedAmount?: number
  actualAmount?: number
  currency: string
  dueDate: Date
  paidDate?: Date
  status: "pending" | "paid" | "overdue" | "skipped"
  transactionId?: string // Link to actual transaction once paid
  createdAt: Date
  updatedAt: Date
  version: number
}

export type AssetKind = "asset" | "liability";

export type AssetValuationMethod = "manual" | "market" | "calculated";

export type AssetValuationSource = "manual" | "market" | "imported";

export type AssetCategory =
  | "real_estate"
  | "vehicle"
  | "gold"
  | "crypto"
  | "investment"
  | "cash"
  | "other"
  | "mortgage"
  | "student_loan"
  | "auto_loan"
  | "personal_loan"
  | "credit_card";

export type AssetStatus = "active" | "archived";

export interface Asset {
  _id: ObjectId;
  userId: string;
  organizationId: string | null;
  name: string;
  kind: AssetKind;
  category: AssetCategory;
  currency: string;
  currentValue: number; // Stored in cents/paise
  valuationMethod: AssetValuationMethod;
  ownershipPercentage: number;
  acquiredAt?: Date;
  notes?: string;
  status: AssetStatus;
  isArchived: boolean;
  createdAt: Date;
  updatedAt: Date;
  version: number;
}

export interface AssetValuation {
  _id: ObjectId;
  assetId: string;
  userId: string;
  organizationId: string | null;
  date: Date;
  value: number; // Stored in cents/paise
  source: AssetValuationSource;
  notes?: string;
  createdAt: Date;
}

export interface NetWorthBreakdown {
  netWorth: number;
  totalAssets: number;
  totalLiabilities: number;
  assetsBreakdown: {
    cash: number;
    bank: number;
    investments: number;
    loans: number;
    manualAssets: number;
  };
  liabilitiesBreakdown: {
    creditCards: number;
    loans: number;
    manualLiabilities: number;
  };
  currencyBreakdown: Record<string, { assets: number; liabilities: number; netWorth: number }>;
}

export interface HistoricalNetWorthPoint extends NetWorthBreakdown {
  date: Date;
  dateStr: string;
}

export interface NetWorthHolding {
  id: string
  name: string
  source: "wallet" | "loan" | "asset"
  kind: "asset" | "liability"
  category: string
  currentValue: number     // Converted to base currency, stored in cents
  percentage: number       // Percentage of total assets (or total liabilities)
  currency: string         // Base currency
  originalValue: number    // Value in original currency
  originalCurrency: string
  icon: string             // Icon name string
  href?: string            // Path to detail page (/wallets/[id], /loans/[id], etc.)
}

export interface NetWorthActivityEvent {
  id: string
  type: "valuation" | "repayment" | "new_loan" | "new_asset" | "transaction"
  date: Date
  title: string
  description: string
  amount?: number          // Value in original currency
  currency?: string
  href?: string
}

export interface NetWorthInsight {
  id: string
  type: "info" | "warning" | "success"
  text: string
  metric?: string
  href?: string
}

export interface NetWorthOverviewViewModel {
  currency: string
  netWorth: number
  totalAssets: number
  totalLiabilities: number
  moMChangePct: number
  largestAsset?: { name: string; value: number }
  
  // Health Metrics
  liquidityRatio: number
  debtRatio: number
  largestLiability?: { name: string; value: number }
  netWorthTrend: "up" | "down" | "flat"

  // Holdings Lists
  topAssets: NetWorthHolding[]
  topLiabilities: NetWorthHolding[]

  // Activity & Insights
  recentActivity: NetWorthActivityEvent[]
  insights: NetWorthInsight[]
}

export interface InvestmentHolding {
  _id: ObjectId
  userId: string
  organizationId: string | null
  walletId: string
  symbol: string
  name: string
  assetType: "stock" | "etf" | "crypto" | "mutual_fund" | "bond" | "commodity" | "other"
  quantity: number
  averageCostBasis: number
  totalCostBasis: number
  currentPrice: number
  status: "active" | "closed"
  realizedGain: number
  currency: string
  exchange?: string
  isin?: string
  cusip?: string
  metadata?: Record<string, unknown>
  createdAt: Date
  updatedAt: Date
}

export type InvestmentTransactionType =
  | "buy"
  | "sell"
  | "cash_dividend"
  | "reinvested_dividend"
  | "stock_split"
  | "reverse_split"
  | "interest"
  | "fee"
  | "transfer_in"
  | "transfer_out"
  | "adjustment"

export interface InvestmentTransaction {
  _id: ObjectId
  userId: string
  organizationId: string | null
  walletId: string
  holdingId: string
  symbol: string
  assetType: "stock" | "etf" | "crypto" | "mutual_fund" | "bond" | "commodity" | "other"
  type: InvestmentTransactionType
  quantity: number
  price: number
  grossAmount: number
  fees: number
  cashImpact: number
  realizedGain?: number
  dividendAmount?: number
  date: Date
  notes?: string
  metadata?: Record<string, unknown>
  createdAt: Date
  updatedAt: Date
}

export interface InvestmentPrice {
  _id: ObjectId
  holdingId: string
  price: number
  date: Date
  source: "manual" | "market"
  createdAt: Date
}

export interface Watchlist {
  _id: ObjectId
  userId: string
  organizationId: string | null
  name: string
  description?: string
  color?: string
  icon?: string
  sortOrder: number
  status: "active" | "archived"
  archivedAt?: Date
  metadata?: Record<string, unknown>
  createdAt: Date
  updatedAt: Date
}

export interface WatchlistItem {
  _id: ObjectId
  watchlistId: string
  symbol: string
  name: string
  assetType: "stock" | "etf" | "crypto" | "mutual_fund" | "bond" | "commodity" | "other"
  sortOrder: number
  exchange?: string
  isin?: string
  cusip?: string
  notes?: string
  targetPrice?: number
  targetDirection?: "above" | "below"
  alertEnabled?: boolean
  lastAlertTriggeredAt?: Date
  metadata?: Record<string, unknown>
  createdAt: Date
  updatedAt: Date
}

// ==========================================
// Shared Expenses & Settlement Domain Types
// ==========================================

export type ParticipantType = "user" | "contact"

export interface SharedExpenseParticipant {
  participantId: string
  participantType: ParticipantType
  name: string
  email?: string
  amountOwed: number      // In smallest currency unit (cents / paise)
  amountPaid: number      // In smallest currency unit
  percentage?: number     // Optional stored percentage for % split mode
}

export type SharedExpenseStatus = "unsettled" | "partially_settled" | "settled"

export interface SharedExpense {
  _id: ObjectId
  userId: string                    // Creator/Owner user ID
  organizationId: string | null     // Shared Space ID if scope is group space
  transactionId?: string            // Optional link to wallet transaction
  title: string
  totalAmount: number               // In smallest currency unit (cents / paise)
  currency: string                  // ISO 4217 code
  paidByParticipantId: string       // User ID or Contact ID who paid upfront
  paidByParticipantType: ParticipantType
  splitMode: "equal" | "percentage" | "custom"
  participants: SharedExpenseParticipant[]
  status: SharedExpenseStatus
  date: Date
  notes?: string
  createdAt: Date
  updatedAt: Date
  version: number
}

export interface SharedSettlement {
  _id: ObjectId
  userId: string                    // Creator/Record owner
  organizationId: string | null     // Shared Space ID if applicable
  expenseId?: string                // Optional link to a specific SharedExpense
  fromParticipantId: string         // Payer participant ID
  fromParticipantType: ParticipantType
  fromParticipantName?: string      // Payer display name
  toParticipantId: string           // Receiver participant ID
  toParticipantType: ParticipantType
  toParticipantName?: string        // Receiver display name
  amount: number                    // Amount settled in cents/paise
  currency: string
  paymentMethod?: string            // "cash", "upi", "bank_transfer", "other"
  transactionId?: string            // Optional linked wallet transaction
  settledAt: Date
  notes?: string
  createdAt: Date
}

// View Models for Shared Expenses UI

export interface PairwiseBalance {
  fromParticipantId: string
  fromParticipantName: string
  fromParticipantType: ParticipantType
  toParticipantId: string
  toParticipantName: string
  toParticipantType: ParticipantType
  netAmount: number                // In cents. Positive means 'from' owes 'to'
  currency: string
}

export interface ParticipantSummary {
  id: string
  type: ParticipantType
  name: string
  email?: string
  totalPaid: number                // Total paid across expenses
  totalShare: number               // Total expense share owed
  netBalance: number               // >0 means owed to participant, <0 means owes money
  currency: string
}

export interface SimplifiedDebtTransfer {
  fromParticipantId: string
  fromParticipantName: string
  fromParticipantType: ParticipantType
  toParticipantId: string
  toParticipantName: string
  toParticipantType: ParticipantType
  amount: number                    // In cents
  currency: string
}

export interface SharedExpensesOverviewViewModel {
  currency: string
  totalSharedAmount: number         // Total volume of shared expenses
  userNetBalance: number            // Current user's net position (>0: user is owed, <0: user owes)
  userTotalOwedToOthers: number     // Sum of money user owes
  userTotalOwedFromOthers: number   // Sum of money owed to user
  activeExpenseCount: number
  participants: ParticipantSummary[]
  pairwiseBalances: PairwiseBalance[]
  simplifiedTransfers: SimplifiedDebtTransfer[]
  recentExpenses: SharedExpense[]
  recentSettlements: SharedSettlement[]
}

// ── Financial Planner & Forecasting Types ──

export interface PlannerScenario {
  _id: ObjectId
  userId: string
  name: string
  description?: string
  isDefault?: boolean
  monthlyIncomeAdjustment: number    // In cents (+ or -)
  monthlyExpenseAdjustment: number   // In cents (+ or -)
  extraLoanRepayment: number         // In cents (+ applied monthly to loans)
  extraGoalContribution: number      // In cents (+ applied monthly to active goals)
  pausedRecurringIds: string[]       // Array of RecurringRule _id strings
  investmentReturnRate: number       // Annual ROI % (e.g., 7 for 7%)
  savingsApy?: number                // High-yield savings APY % (e.g., 4 for 4%)
  horizonMonths: number              // Horizon in months (e.g. 6, 12, 24, 36, 60)
  createdAt: Date
  updatedAt: Date
}

export interface SerializedPlannerScenario {
  _id: string
  userId: string
  name: string
  description?: string
  isDefault?: boolean
  monthlyIncomeAdjustment: number
  monthlyExpenseAdjustment: number
  extraLoanRepayment: number
  extraGoalContribution: number
  pausedRecurringIds: string[]
  investmentReturnRate: number
  savingsApy?: number
  horizonMonths: number
  createdAt: string
  updatedAt: string
}

export interface ForecastPoint {
  monthIndex: number                 // 0 = current month, 1 = next month, etc.
  date: Date
  dateStr: string                    // "MMM yy" e.g. "Aug 26"
  
  // Dual-series values (Baseline vs Simulated Scenario)
  baselineLiquidCash: number         // In cents
  simulatedLiquidCash: number        // In cents
  
  baselineNetWorth: number           // In cents
  simulatedNetWorth: number          // In cents
  
  baselineMonthlyIncome: number      // In cents
  simulatedMonthlyIncome: number     // In cents
  
  baselineMonthlyExpense: number     // In cents
  simulatedMonthlyExpense: number    // In cents

  baselineTotalDebt: number          // In cents
  simulatedTotalDebt: number         // In cents

  baselineGoalSavings: number        // In cents
  simulatedGoalSavings: number       // In cents
}

export interface GoalMilestone {
  goalId: string
  goalName: string
  targetAmount: number               // In cents
  currentAmount: number              // In cents
  baselineCompletionDateStr: string | null // e.g. "Nov 26" or "Beyond horizon"
  simulatedCompletionDateStr: string | null
  monthsSaved: number                // Baseline vs Simulated difference
}

export interface LoanMilestone {
  loanId: string
  loanName: string
  originalBalance: number            // In cents
  currentBalance: number             // In cents
  baselinePayoffDateStr: string | null
  simulatedPayoffDateStr: string | null
  monthsSaved: number
}

export interface PlannerInsight {
  id: string
  type: "positive" | "warning" | "info"
  title: string
  description: string
  metricImpact?: string
}

export interface ForecastResult {
  targetCurrency: string
  horizonMonths: number
  currentNetWorth: number            // In cents
  currentLiquidCash: number           // In cents
  projectedBaseline12MNetWorth: number// In cents
  projectedSimulated12MNetWorth: number// In cents
  baselineDebtFreeDateStr: string | null
  simulatedDebtFreeDateStr: string | null
  emergencyReserveMonths: number     // Baseline liquid cash / monthly expense
  points: ForecastPoint[]
  goalMilestones: GoalMilestone[]
  loanMilestones: LoanMilestone[]
  insights: PlannerInsight[]
}

// ── Financial Health Score Domain Types ──

export type HealthTier = "excellent" | "good" | "fair" | "needs_attention"
export type PillarId = "liquidity" | "savings" | "debt" | "budget" | "growth"

export interface PillarMetric {
  label: string
  value: string
  target: string
  status: "positive" | "neutral" | "negative"
}

export interface PillarScore {
  id: PillarId
  title: string
  score: number           // 0 to 20
  maxScore: 20
  weight: number          // 20%
  tier: HealthTier
  summary: string
  metrics: PillarMetric[]
}

export interface HealthRecommendation {
  id: string
  pillarId: PillarId
  title: string
  description: string
  potentialPoints: number // e.g. +5 pts
  priority: "high" | "medium" | "low"
  actionUrl?: string
  actionLabel?: string
}

export interface MonthlyHealthTrend {
  month: string           // "YYYY-MM"
  label: string           // "MMM" e.g. "Aug"
  overallScore: number
  tier: HealthTier
}

export interface FinancialHealthData {
  overallScore: number    // 0 to 100
  tier: HealthTier
  previousMonthScore: number
  scoreDelta: number      // e.g. +3 or -2
  currency: string
  pillars: Record<PillarId, PillarScore>
  recommendations: HealthRecommendation[]
  historicalTrend: MonthlyHealthTrend[]
}

// ── AI Spending Insights Domain Types ──

export type InsightSeverity = "critical" | "warning" | "opportunity" | "info"

export type InsightCategory =
  | "spikes"
  | "outliers"
  | "subscriptions"
  | "savings"
  | "cashflow"
  | "income"

export interface SpendingInsight {
  id: string                     // Stable deterministic fingerprint (e.g. "spike_dining_out_2026_09")
  category: InsightCategory
  severity: InsightSeverity
  title: string
  description: string
  metricImpact?: number          // Amount in cents/paise (positive or negative)
  metricLabel?: string           // e.g. "+38% vs baseline" or "$142.00 surge"
  actionLabel?: string           // e.g. "Review Transactions", "Adjust Budget", "Manage Recurring"
  actionUrl?: string             // e.g. "/transactions?categoryId=...", "/recurring"
  tags?: string[]
  score: number                  // 0 to 100 for deterministic ranking & priority
  detectedAt: Date
  isBookmarked?: boolean
}

export interface UserInsightState {
  _id: ObjectId
  userId: string
  organizationId?: string | null
  insightKey: string             // Matches SpendingInsight.id
  status: "active" | "dismissed" | "bookmarked"
  dismissedAt?: Date
  bookmarkedAt?: Date
  updatedAt: Date
}

export interface SpendingInsightsData {
  executiveBriefing: {
    summary: string
    focalAdvice: string
    isAiGenerated: boolean
  }
  insights: SpendingInsight[]
  bookmarkedInsights: SpendingInsight[]
  dismissedCount: number
  metrics: {
    activeCount: number
    anomalyCount: number
    potentialSavingsMonthlyCents: number
    discretionarySurgeCents: number
  }
  currency: string
}

// ── Cash Flow Calendar Domain Types ──

export type CalendarEventType =
  | "transaction"
  | "recurring"
  | "bill"
  | "subscription"
  | "loan"
  | "plan"

export type CalendarEventStatus = "settled" | "upcoming" | "overdue" | "planned"

export interface CalendarEventItem {
  id: string
  date: string                   // YYYY-MM-DD
  title: string
  amount: number                 // Original currency cents (always positive)
  currency: string
  convertedAmount: number        // Target currency cents
  type: CalendarEventType
  flow: "inflow" | "outflow"
  status: CalendarEventStatus
  category?: {
    id: string
    name: string
    icon?: string
    color?: string
  }
  walletId?: string
  walletName?: string
  sourceId?: string
  notes?: string
}

export interface CalendarDaySummary {
  date: string                   // YYYY-MM-DD
  dayOfMonth: number
  isCurrentMonth: boolean
  isToday: boolean
  isPast: boolean
  closingBalance: number         // Target currency cents
  totalInflow: number            // Target currency cents
  totalOutflow: number           // Target currency cents
  netChange: number              // totalInflow - totalOutflow
  events: CalendarEventItem[]
  isDeficit: boolean             // closingBalance < 0
  isLowBuffer: boolean           // closingBalance < safetyBuffer
}

export interface CashFlowMonthOverview {
  month: string                  // YYYY-MM
  targetCurrency: string
  startingBalance: number        // Opening balance on day 1 of month
  projectedEndingBalance: number // Closing balance on last day of month
  totalInflow: number            // Sum of month inflows
  totalOutflow: number           // Sum of month outflows
  netCashFlow: number            // totalInflow - totalOutflow
  lowestBalance: number          // Minimum projected balance in month
  lowestBalanceDate: string      // Date of minimum balance
  deficitDaysCount: number       // Days with closingBalance < 0
  days: CalendarDaySummary[]     // Complete calendar cells (35 or 42)
}

export interface CalendarPlanEvent {
  _id: ObjectId
  userId: string
  organizationId?: string | null
  ownerUserId?: string
  title: string
  amount: number                 // in cents
  currency: string
  date: Date                     // Scheduled execution date
  flow: "inflow" | "outflow"
  walletId?: string
  categoryId?: string
  notes?: string
  isCompleted: boolean
  createdAt: Date
  updatedAt: Date
}

export interface SerializedCalendarPlanEvent extends Omit<CalendarPlanEvent, "_id" | "date" | "createdAt" | "updatedAt"> {
  _id: string
  date: string
  createdAt: string
  updatedAt: string
}

// Re-export Search domain types
export * from "./search"

// ── Dashboard Focus Domain Types ──

export interface DashboardFocusCounts {
  overdueBillsCount: number
  overdueBillsAmount: number
  upcomingRenewalsCount: number
  pendingLoansCount: number
  unreadNotificationsCount: number
  baseCurrency: string
}

// ── Financial Timeline Domain Types ──

export type TimelineEventType =
  | "transaction"
  | "goal_milestone"
  | "goal_completed"
  | "loan_originated"
  | "loan_repayment"
  | "loan_settled"
  | "bill_paid"
  | "subscription_renewed"
  | "investment_trade"
  | "dividend_received"
  | "shared_settlement"
  | "asset_created"
  | "asset_revaluation"

export type TimelineEventCategory =
  | "all"
  | "milestones"
  | "transactions"
  | "bills_subscriptions"
  | "investments"
  | "loans"
  | "shared"

export type TimelineEventImpact = "inflow" | "outflow" | "neutral" | "milestone"

export interface TimelineEventBadge {
  label: string
  variant?: "default" | "secondary" | "destructive" | "outline" | "success"
}

export interface TimelineEvent {
  id: string
  type: TimelineEventType
  category: TimelineEventCategory
  title: string
  description: string
  date: string // ISO date string for safe RSC -> Client serialization
  amount?: number // in cents/paise (positive integer; impact defines direction)
  currency?: string
  impact: TimelineEventImpact
  iconName: string
  badge?: TimelineEventBadge
  isMilestone: boolean
  milestoneReason?: string
  href?: string
  metadata?: Record<string, unknown>
}

export interface TimelineDateGroup {
  label: string // "Today", "Yesterday", "This Week", "Earlier this Month", "August 2026", etc.
  dateKey: string // YYYY-MM-DD or YYYY-MM
  netAmount: number // net cash flow for this date group in cents
  events: TimelineEvent[]
}

export interface TimelineSummaryStats {
  totalEvents: number
  milestonesCount: number
  totalInflow: number // in cents
  totalOutflow: number // in cents
  netFlow: number // in cents
  currency: string
}

export interface TimelineData {
  events: TimelineEvent[]
  groups: TimelineDateGroup[]
  stats: TimelineSummaryStats
  currency: string
}

// ── AI Financial Coach Domain Types ──

export type CoachStrategyCategory =
  | "emergency_fund"
  | "debt_payoff"
  | "goal_acceleration"
  | "budget_tuning"
  | "subscription_trim"
  | "wealth_diversification"

export type CoachStrategyImpact = "high" | "medium" | "easy_win"

export interface CoachStrategy {
  id: string
  category: CoachStrategyCategory
  impact: CoachStrategyImpact
  title: string
  subtitle: string
  primaryMetric: {
    label: string
    value: string
    delta?: string
  }
  description: string
  actionLabel: string
  actionUrl: string
  score: number
  details: {
    currentValue: number
    projectedValue: number
    monthlyBenefitCents: number
    timelineImpactMonths?: number
  }
}

export interface EmergencyFundAnalysis {
  liquidSavingsCents: number
  monthlyBurnRateCents: number
  currentRunwayMonths: number
  targetRunwayMonths: number
  shortfallCents: number
  healthTier: "critical" | "warning" | "adequate" | "healthy" | "exceptional"
}

export interface DebtPayoffComparison {
  totalDebtCents: number
  activeLoanCount: number
  currentPayoffMonths: number
  acceleratedPayoffMonths: number
  monthsSaved: number
  interestSavedCents: number
  snowballPriorityLoan?: {
    loanId: string
    name: string
    balanceCents: number
  }
  avalanchePriorityLoan?: {
    loanId: string
    name: string
    balanceCents: number
  }
}

export interface GoalAccelerationItem {
  goalId: string
  name: string
  targetCents: number
  currentCents: number
  status: "ahead" | "on_track" | "behind"
  requiredMonthlyCents: number
  currentMonthlyRunRateCents: number
  suggestedMonthlyBoostCents: number
}

export interface CoachMessage {
  _id: ObjectId
  userId: string
  organizationId?: string | null
  role: "user" | "coach"
  content: string
  createdAt: Date
}

export interface SerializedCoachMessage {
  _id: string
  userId: string
  organizationId?: string | null
  role: "user" | "coach"
  content: string
  createdAt: string
}

export interface CoachSummaryBrief {
  headline: string
  focalAdvice: string
  keyHighlights: string[]
  isAiGenerated: boolean
}

export interface CoachOverviewData {
  metrics: {
    emergencyRunwayMonths: number
    monthsToDebtFree: number | null
    potentialMonthlyOptimizationCents: number
    goalsOnTrackRatio: { onTrack: number; total: number }
    healthScore: number
  }
  summaryBrief: CoachSummaryBrief
  strategies: CoachStrategy[]
  emergencyFund: EmergencyFundAnalysis
  debtComparison: DebtPayoffComparison | null
  goalAccelerations: GoalAccelerationItem[]
  recentChatMessages: SerializedCoachMessage[]
  targetCurrency: string
}

// ── Monthly Financial Review Domain Types ──

export interface MonthlyReviewCategorySpend {
  categoryId: string
  categoryName: string
  categoryIcon?: string
  categoryColor?: string
  amountCents: number
  percentage: number
  previousMonthAmountCents: number
  deltaPercentage: number
}

export interface MonthlyReviewBudgetStatus {
  budgetId: string
  categoryName: string
  budgetAmountCents: number
  spentAmountCents: number
  isOverBudget: boolean
  overrunCents: number
  percentageUsed: number
}

export interface MonthlyReviewGoalContribution {
  goalId: string
  goalName: string
  contributedThisMonthCents: number
  targetAmountCents: number
  currentAmountCents: number
  progressPercentage: number
}

export interface MonthlyReviewLoanPaydown {
  loanId: string
  loanName: string
  principalPaidCents: number
  remainingBalanceCents: number
}

export interface MonthlyReviewTransactionItem {
  id: string
  date: string
  name: string
  amountCents: number
  currency: string
  categoryName?: string
  categoryColor?: string
  walletName?: string
}

export interface MonthlyReviewSummaryBrief {
  headline: string
  summary: string
  highlights: string[]
  concerns: string[]
  recommendations: string[]
  nextMonthOutlook: string
  isAiGenerated: boolean
}

export interface MonthlyReviewData {
  monthKey: string // "YYYY-MM"
  monthLabel: string // "August 2026"
  targetCurrency: string
  metrics: {
    totalIncomeCents: number
    totalExpenseCents: number
    netSavingsCents: number
    savingsRatePercentage: number
    previousMonthIncomeCents: number
    previousMonthExpenseCents: number
    previousMonthSavingsRate: number
    incomeDeltaPercentage: number
    expenseDeltaPercentage: number
    openingNetWorthCents: number
    closingNetWorthCents: number
    netWorthDeltaCents: number
  }
  categoryBreakdown: MonthlyReviewCategorySpend[]
  budgetPerformance: MonthlyReviewBudgetStatus[]
  topExpenses: MonthlyReviewTransactionItem[]
  topIncomes: MonthlyReviewTransactionItem[]
  goalContributions: MonthlyReviewGoalContribution[]
  loanPaydowns: MonthlyReviewLoanPaydown[]
  subscriptionChanges: {
    activeCount: number
    totalMonthlyCostCents: number
  }
  executiveBrief: MonthlyReviewSummaryBrief
  availableMonths: { monthKey: string; label: string }[]
}

export interface LatestCompletedMonthSummary {
  monthKey: string
  monthLabel: string
  savingsRatePercentage: number
  netSavingsCents: number
  targetCurrency: string
  underBudgetCategoryCount: number
  hasTransactions: boolean
}


