import { ObjectId } from "mongodb"

export interface Wallet {
  _id: ObjectId
  userId: string
  name: string
  type: "bank" | "cash" | "credit_card" | "savings" | "investment" | "lent"
  currency: string        // ISO 4217: "USD", "INR", "EUR"
  balance: number         // Store in smallest unit (cents / paise)
  color: string           // Hex color
  icon: string            // Icon name string
  isArchived: boolean
  sharedWith?: string[]   // Array of collaborator emails
  createdAt: Date
  updatedAt: Date
}

export interface Transaction {
  _id: ObjectId
  userId: string
  walletId: string
  categoryId: string
  type: "income" | "expense" | "transfer"
  amount: number          // Always positive; type determines direction
  currency: string
  description: string
  notes?: string
  date: Date              // User-specified date, not createdAt
  tags: string[]
  isRecurring: boolean
  recurringId?: string    // Links to recurring_rules._id if generated by a rule
  linkedTransactionId?: string // Links two transaction records in a transfer
  transferType?: "debit" | "credit" // Determines if this transaction is the source (debit) or destination (credit) of a transfer
  goalId?: string         // Optional link to a Goal document for savings goals contributions
  createdAt: Date
  updatedAt: Date
}

export interface Category {
  _id: ObjectId
  userId: string | null   // null = system default (shared); string = user-owned
  name: string
  type: ("income" | "expense" | "transfer")[]
  icon: string
  color: string
  parentId?: string       // For subcategories
  isDefault: boolean
  createdAt: Date
}

export interface Budget {
  _id: ObjectId
  userId: string
  categoryId: string
  walletId?: string       // undefined = applies across all wallets
  name: string
  amount: number
  currency: string
  period: "daily" | "weekly" | "monthly" | "yearly"
  startDate: Date
  endDate?: Date
  isActive: boolean
  alertThreshold: number  // 0–100; alert when spending % hits this value
  createdAt: Date
  updatedAt: Date
}

export interface RecurringRule {
  _id: ObjectId
  userId: string
  walletId: string
  categoryId: string
  type: "income" | "expense"
  amount: number
  currency: string
  description: string
  frequency: "daily" | "weekly" | "biweekly" | "monthly" | "quarterly" | "yearly"
  startDate: Date
  endDate?: Date
  nextDueDate: Date
  lastProcessedDate?: Date
  isActive: boolean
  tags: string[]
  createdAt: Date
  updatedAt: Date
}

export interface ExchangeRate {
  _id: ObjectId
  base: string
  rates: Record<string, number>
  updatedAt: Date
}

export interface User {
  id: string
  email: string
  name: string
  emailVerified: boolean
  image?: string
  createdAt: Date
  updatedAt: Date
  role: "admin" | "user"
  banned?: boolean
  banReason?: string
  banExpires?: Date
  twoFactorEnabled?: boolean
  approved: boolean
}

export interface Session {
  id: string
  userId: string
  expiresAt: Date
  token: string
  createdAt: Date
  updatedAt: Date
  ipAddress?: string
  userAgent?: string
  impersonatedBy?: string
}

export interface Goal {
  _id: ObjectId
  userId: string
  name: string
  targetAmount: number     // stored in lowest currency units (e.g. cents)
  currentAmount: number    // stored in lowest currency units
  currency: string         // ISO 4217 code
  targetDate: Date
  walletId?: string        // optional associated wallet
  color: string
  icon: string
  createdAt: Date
  updatedAt: Date
}
