import { ObjectId } from "mongodb"

export interface Wallet {
  _id: ObjectId
  userId: string
  name: string
  type: "bank" | "cash" | "credit_card" | "savings" | "investment" | "lent"
  currency: string        // ISO 4217: "USD", "INR", "EUR"
  balance: number         // Store in smallest unit (cents / paise)
  color: string           // Hex color
  icon: string            // Icon name string
  isArchived: boolean
  createdAt: Date
  updatedAt: Date
  organizationId?: string | null
  ownerUserId?: string
  createdBy?: string
  updatedBy?: string
  version?: number
}

export interface Transaction {
  _id: ObjectId
  userId: string
  walletId: string
  categoryId?: string | null
  type: "income" | "expense" | "transfer"
  amount: number          // Always positive; type determines direction
  currency: string
  description: string
  notes?: string
  date: Date              // User-specified date, not createdAt
  tags: string[]
  isRecurring: boolean
  recurringId?: string    // Links to recurring_rules._id if generated by a rule
  linkedTransactionId?: string // Links two transaction records in a transfer
  transferType?: "debit" | "credit" // Determines if this transaction is the source (debit) or destination (credit) of a transfer
  goalId?: string         // Optional link to a Goal document for savings goals contributions
  budgetId?: string | null // Optional link to a Budget override
  isFlagged?: boolean
  needsReview?: boolean
  splitMode?: "amount" | "percentage" | "equal"
  splits?: { id: string; categoryId: string; amount: number; percentage?: number; notes?: string }[]
  loanId?: string
  isLoanPrincipal?: boolean
  createdAt: Date
  updatedAt: Date
  organizationId?: string | null
  ownerUserId?: string
  createdBy?: string
  updatedBy?: string
  version?: number
}

export interface Category {
  _id: ObjectId
  userId: string | null   // null = system default (shared); string = user-owned
  name: string
  type: ("income" | "expense" | "transfer")[]
  icon: string
  color: string
  parentId?: string       // For subcategories
  isDefault: boolean
  createdAt: Date
  updatedAt?: Date
  organizationId?: string | null
  ownerUserId?: string
  createdBy?: string
  updatedBy?: string
  version?: number
}

export interface Budget {
  _id: ObjectId
  userId: string
  categoryId: string
  walletId?: string       // undefined = applies across all wallets
  name: string
  amount: number
  currency: string
  period: "daily" | "weekly" | "monthly" | "yearly"
  startDate: Date
  endDate?: Date
  isActive: boolean
  alertThreshold: number  // 0–100; alert when spending % hits this value
  createdAt: Date
  updatedAt: Date
  organizationId?: string | null
  ownerUserId?: string
  createdBy?: string
  updatedBy?: string
  version?: number
}

export interface RecurringRule {
  _id: ObjectId
  userId: string
  walletId: string
  categoryId: string
  type: "income" | "expense"
  amount: number
  currency: string
  description: string
  frequency: "daily" | "weekly" | "biweekly" | "monthly" | "quarterly" | "yearly"
  startDate: Date
  endDate?: Date
  nextDueDate: Date
  lastProcessedDate?: Date
  isActive: boolean
  tags: string[]
  createdAt: Date
  updatedAt: Date
  organizationId?: string | null
  ownerUserId?: string
  createdBy?: string
  updatedBy?: string
  version?: number
  
  // Subscription / Bill specific fields
  kind?: "recurring" | "subscription" | "bill"
  providerName?: string
  providerUrl?: string
  cancellationUrl?: string
  trialEndDate?: Date
  reminderDaysBefore?: number
  nextRenewalDate?: Date
  lastRenewalDate?: Date
  renewalPrice?: number
  cancelledAt?: Date
  cancelReason?: string
  status?: "active" | "trial" | "paused" | "cancelled" | "expired"
  lastReminderSentAt?: Date
}

export interface ExchangeRate {
  _id: ObjectId
  base: string
  rates: Record<string, number>
  updatedAt: Date
}

export interface User {
  id: string
  email: string
  name: string
  emailVerified: boolean
  image?: string
  createdAt: Date
  updatedAt: Date
  role: "admin" | "user"
  banned?: boolean
  banReason?: string
  banExpires?: Date
  twoFactorEnabled?: boolean
  approved: boolean
}

export interface Session {
  id: string
  userId: string
  expiresAt: Date
  token: string
  createdAt: Date
  updatedAt: Date
  ipAddress?: string
  userAgent?: string
  impersonatedBy?: string
}

export interface Goal {
  _id: ObjectId
  userId: string
  name: string
  targetAmount: number     // stored in lowest currency units (e.g. cents)
  currentAmount: number    // stored in lowest currency units
  currency: string         // ISO 4217 code
  targetDate: Date
  walletId?: string        // optional associated wallet
  color: string
  icon: string
  createdAt: Date
  updatedAt: Date
  organizationId?: string | null
  ownerUserId?: string
  createdBy?: string
  updatedBy?: string
  version?: number
}

export type SpaceType = "family" | "couple" | "business" | "travel" | "roommates" | "other";

export interface OrganizationSettings {
  _id: ObjectId;
  organizationId: string;
  baseCurrency: string;
  fiscalYearStartMonth: number;
  spaceType: SpaceType;
  updatedBy: string;
  updatedAt: Date;
  version: number;
}

export interface Notification {
  _id: ObjectId;
  userId: string;
  title: string;
  message: string;
  type: string;
  link?: string;
  image?: string;
  readAt?: Date;
  dismissedAt?: Date;
  archivedAt?: Date;
  createdAt: Date;
  updatedAt: Date;
}

export interface SerializedNotification {
  _id: string;
  userId: string;
  title: string;
  message: string;
  type: string;
  link?: string | null;
  image?: string | null;
  readAt?: string | null;
  dismissedAt?: string | null;
  archivedAt?: string | null;
  createdAt: string;
  updatedAt: string;
}


export type RuleTrigger = "manual" | "receipt" | "csv_import" | "recurring" | "api";

export type ExecutionMode = "all_matches" | "first_match";

export type ConditionField = "description" | "amount" | "walletId" | "walletType" | "currency" | "tags";

export type ConditionOperator = 
  | "contains" | "equals" | "starts_with" | "ends_with" | "regex"
  | "gt" | "lt" | "eq" | "gte" | "lte"
  | "contains_tag";

export type ConditionValue = string | number | boolean | string[];

export interface RuleCondition {
  field: ConditionField
  operator: ConditionOperator
  value: ConditionValue
}

export type RuleAction = 
  | { type: "assign_category"; categoryId: string }
  | { type: "assign_tags"; tags: string[] }
  | { type: "assign_budget"; budgetId: string }
  | { type: "set_notes"; notes: string }
  | { type: "mark_recurring"; isRecurring: boolean }
  | { type: "flag_transaction"; isFlagged: boolean; needsReview: boolean }
  | { type: "auto_split"; splits: { id?: string; categoryId: string; amount: number; notes?: string }[] }
  | { type: "move_to_wallet"; walletId: string };

export type RuleStatus = "draft" | "active" | "disabled";

export interface AutomationRule {
  _id: ObjectId
  userId: string
  organizationId: string | null
  name: string
  description?: string
  status: RuleStatus
  priority: number           // Higher executes first
  stopProcessing: boolean    // If true, stop subsequent evaluations if this rule matches
  triggers: RuleTrigger[]    // Contexts in which this rule applies
  conditions: RuleCondition[]
  conditionOperator: "and" | "or"
  actions: RuleAction[]
  
  // Statistics
  executionCount: number
  lastExecutedAt: Date | null
  lastMatchedAt: Date | null
  
  version: number
  createdAt: Date
  updatedAt: Date
  createdBy: string
  updatedBy: string
}

export interface RuleConflict {
  field: string
  winningRuleId: string
  winningRuleName: string
  losingRuleId: string
  losingRuleName: string
  valueAttempted: unknown
  valueApplied: unknown
}

export interface RuleExecutionResult {
  originalTransaction: Partial<Transaction>
  modifiedTransaction: Partial<Transaction>
  matchedRulesCount: number
  appliedRules: {
    ruleId: string
    ruleName: string
    actionsApplied: RuleAction[]
  }[]
  skippedRules: {
    ruleId: string
    ruleName: string
    reason: "stop_processing_triggered" | "trigger_mismatch" | "disabled" | "condition_mismatch"
  }[]
  conflicts: RuleConflict[]
  warnings: string[]
  stopProcessingTriggered: boolean
}

export interface AutomationJob {
  _id: ObjectId
  userId: string
  organizationId: string | null
  ruleId: string
  status: "pending" | "processing" | "completed" | "failed"
  totalTransactions: number
  processedTransactions: number
  matchedTransactions: number
  error?: string
  createdAt: Date
  updatedAt: Date
}

export interface Contact {
  _id: ObjectId
  userId: string
  organizationId: string | null
  name: string
  email?: string
  phone?: string
  notes?: string
  metadata?: Record<string, unknown>
  createdAt: Date
  updatedAt: Date
  version: number
}

export interface Loan {
  _id: ObjectId
  userId: string
  organizationId: string | null
  type: "lent" | "borrowed"
  contactId: string
  personName: string
  amount: number
  currency: string
  interestRate?: number
  walletId: string
  transactionId: string
  date: Date
  dueDate?: Date
  notes?: string
  status: "active" | "partially_repaid" | "fully_repaid" | "overdue" | "cancelled"
  remainingAmount: number
  reminderSchedule: number[]
  sentReminders: number[]
  lastOverdueReminderSentAt?: Date
  metadata?: Record<string, unknown>
  createdAt: Date
  updatedAt: Date
  version: number
}

export interface LoanRepayment {
  _id: ObjectId
  loanId: string
  transactionId: string
  amount: number
  date: Date
  notes?: string
  createdAt: Date
}

export interface BillInstance {
  _id: ObjectId
  userId: string
  organizationId?: string | null
  ruleId: string // Reference to the RecurringRule template
  description: string
  expectedAmount?: number
  actualAmount?: number
  currency: string
  dueDate: Date
  paidDate?: Date
  status: "pending" | "paid" | "overdue" | "skipped"
  transactionId?: string // Link to actual transaction once paid
  createdAt: Date
  updatedAt: Date
  version: number
}

export type AssetKind = "asset" | "liability";

export type AssetValuationMethod = "manual" | "market" | "calculated";

export type AssetValuationSource = "manual" | "market" | "imported";

export type AssetCategory =
  | "real_estate"
  | "vehicle"
  | "gold"
  | "crypto"
  | "investment"
  | "cash"
  | "other"
  | "mortgage"
  | "student_loan"
  | "auto_loan"
  | "personal_loan"
  | "credit_card";

export type AssetStatus = "active" | "archived";

export interface Asset {
  _id: ObjectId;
  userId: string;
  organizationId: string | null;
  name: string;
  kind: AssetKind;
  category: AssetCategory;
  currency: string;
  currentValue: number; // Stored in cents/paise
  valuationMethod: AssetValuationMethod;
  ownershipPercentage: number;
  acquiredAt?: Date;
  notes?: string;
  status: AssetStatus;
  isArchived: boolean;
  createdAt: Date;
  updatedAt: Date;
  version: number;
}

export interface AssetValuation {
  _id: ObjectId;
  assetId: string;
  userId: string;
  organizationId: string | null;
  date: Date;
  value: number; // Stored in cents/paise
  source: AssetValuationSource;
  notes?: string;
  createdAt: Date;
}

export interface NetWorthBreakdown {
  netWorth: number;
  totalAssets: number;
  totalLiabilities: number;
  assetsBreakdown: {
    cash: number;
    bank: number;
    investments: number;
    loans: number;
    manualAssets: number;
  };
  liabilitiesBreakdown: {
    creditCards: number;
    loans: number;
    manualLiabilities: number;
  };
  currencyBreakdown: Record<string, { assets: number; liabilities: number; netWorth: number }>;
}

export interface HistoricalNetWorthPoint extends NetWorthBreakdown {
  date: Date;
  dateStr: string;
}

export interface NetWorthHolding {
  id: string
  name: string
  source: "wallet" | "loan" | "asset"
  kind: "asset" | "liability"
  category: string
  currentValue: number     // Converted to base currency, stored in cents
  percentage: number       // Percentage of total assets (or total liabilities)
  currency: string         // Base currency
  originalValue: number    // Value in original currency
  originalCurrency: string
  icon: string             // Icon name string
  href?: string            // Path to detail page (/wallets/[id], /loans/[id], etc.)
}

export interface NetWorthActivityEvent {
  id: string
  type: "valuation" | "repayment" | "new_loan" | "new_asset" | "transaction"
  date: Date
  title: string
  description: string
  amount?: number          // Value in original currency
  currency?: string
  href?: string
}

export interface NetWorthInsight {
  id: string
  type: "info" | "warning" | "success"
  text: string
  metric?: string
  href?: string
}

export interface NetWorthOverviewViewModel {
  currency: string
  netWorth: number
  totalAssets: number
  totalLiabilities: number
  moMChangePct: number
  largestAsset?: { name: string; value: number }
  
  // Health Metrics
  liquidityRatio: number
  debtRatio: number
  largestLiability?: { name: string; value: number }
  netWorthTrend: "up" | "down" | "flat"

  // Holdings Lists
  topAssets: NetWorthHolding[]
  topLiabilities: NetWorthHolding[]

  // Activity & Insights
  recentActivity: NetWorthActivityEvent[]
  insights: NetWorthInsight[]
}

export interface InvestmentHolding {
  _id: ObjectId
  userId: string
  organizationId: string | null
  walletId: string
  symbol: string
  name: string
  assetType: "stock" | "etf" | "crypto" | "mutual_fund" | "bond" | "commodity" | "other"
  quantity: number
  averageCostBasis: number
  totalCostBasis: number
  currentPrice: number
  status: "active" | "closed"
  realizedGain: number
  currency: string
  exchange?: string
  isin?: string
  cusip?: string
  metadata?: Record<string, unknown>
  createdAt: Date
  updatedAt: Date
}

export type InvestmentTransactionType =
  | "buy"
  | "sell"
  | "cash_dividend"
  | "reinvested_dividend"
  | "stock_split"
  | "reverse_split"
  | "interest"
  | "fee"
  | "transfer_in"
  | "transfer_out"
  | "adjustment"

export interface InvestmentTransaction {
  _id: ObjectId
  userId: string
  organizationId: string | null
  walletId: string
  holdingId: string
  symbol: string
  assetType: "stock" | "etf" | "crypto" | "mutual_fund" | "bond" | "commodity" | "other"
  type: InvestmentTransactionType
  quantity: number
  price: number
  grossAmount: number
  fees: number
  cashImpact: number
  realizedGain?: number
  dividendAmount?: number
  date: Date
  notes?: string
  metadata?: Record<string, unknown>
  createdAt: Date
}

export interface InvestmentPrice {
  _id: ObjectId
  holdingId: string
  price: number
  date: Date
  source: "manual" | "market"
  createdAt: Date
}

export interface Watchlist {
  _id: ObjectId
  userId: string
  organizationId: string | null
  name: string
  description?: string
  color?: string
  icon?: string
  sortOrder: number
  status: "active" | "archived"
  archivedAt?: Date
  metadata?: Record<string, unknown>
  createdAt: Date
  updatedAt: Date
}

export interface WatchlistItem {
  _id: ObjectId
  watchlistId: string
  symbol: string
  name: string
  assetType: "stock" | "etf" | "crypto" | "mutual_fund" | "bond" | "commodity" | "other"
  sortOrder: number
  exchange?: string
  isin?: string
  cusip?: string
  notes?: string
  targetPrice?: number
  targetDirection?: "above" | "below"
  alertEnabled?: boolean
  lastAlertTriggeredAt?: Date
  metadata?: Record<string, unknown>
  createdAt: Date
  updatedAt: Date
}


