import { BudgetTemplate } from "@/types"

export const SYSTEM_BUDGET_TEMPLATES: BudgetTemplate[] = [
  {
    _id: "50-30-20",
    userId: null,
    organizationId: null,
    name: "50/30/20 Balanced Rule",
    tagline: "50% Needs, 30% Wants, 20% Savings & Debt",
    description:
      "The classic personal finance framework popularized by Senator Elizabeth Warren. Divides your income into three clear buckets to balance present enjoyment with long-term financial security.",
    category: "framework",
    methodology: "percentage",
    icon: "Scale",
    color: "#6366f1",
    tags: ["Popular", "Beginner-Friendly", "Balanced"],
    period: "monthly",
    isSystem: true,
    allocations: [
      {
        categoryName: "Housing",
        group: "Needs",
        percentage: 30,
        suggestedColor: "#6366f1",
        suggestedIcon: "Home",
        alertThreshold: 85,
        description: "Rent, mortgage payments, and maintenance.",
      },
      {
        categoryName: "Groceries",
        group: "Needs",
        percentage: 10,
        suggestedColor: "#10b981",
        suggestedIcon: "ShoppingBag",
        alertThreshold: 80,
        description: "Supermarket food, household supplies, and essentials.",
      },
      {
        categoryName: "Utilities & Bills",
        group: "Needs",
        percentage: 5,
        suggestedColor: "#0ea5e9",
        suggestedIcon: "Zap",
        alertThreshold: 90,
        description: "Electricity, water, gas, internet, and mobile.",
      },
      {
        categoryName: "Transportation",
        group: "Needs",
        percentage: 5,
        suggestedColor: "#f59e0b",
        suggestedIcon: "Car",
        alertThreshold: 80,
        description: "Fuel, public transit passes, tolls, and maintenance.",
      },
      {
        categoryName: "Dining Out & Cafes",
        group: "Wants",
        percentage: 15,
        suggestedColor: "#f43f5e",
        suggestedIcon: "Utensils",
        alertThreshold: 80,
        description: "Restaurants, food delivery, cafes, and takeout.",
      },
      {
        categoryName: "Entertainment & Leisure",
        group: "Wants",
        percentage: 10,
        suggestedColor: "#8b5cf6",
        suggestedIcon: "Film",
        alertThreshold: 80,
        description: "Streaming, movies, gaming, hobbies, and social outings.",
      },
      {
        categoryName: "Shopping",
        group: "Wants",
        percentage: 5,
        suggestedColor: "#ec4899",
        suggestedIcon: "Sparkles",
        alertThreshold: 80,
        description: "Clothing, electronics, personal accessories, and impulse buys.",
      },
      {
        categoryName: "Savings & Investments",
        group: "Savings",
        percentage: 20,
        suggestedColor: "#14b8a6",
        suggestedIcon: "PiggyBank",
        alertThreshold: 100,
        description: "Emergency reserves, retirement funds, and wealth building.",
      },
    ],
    rulesSummary: [
      "Keep essential fixed living costs capped under 50% of take-home pay.",
      "Enjoy guilt-free discretionary spending up to 30%.",
      "Automate 20% toward savings, investments, or high-interest debt.",
    ],
    createdAt: new Date("2026-01-01"),
    updatedAt: new Date("2026-01-01"),
  },
  {
    _id: "zero-based",
    userId: null,
    organizationId: null,
    name: "Zero-Based Budget",
    tagline: "Every single currency unit has an assigned purpose",
    description:
      "A discipline where income minus all expenses, savings, and sinking funds equals exactly zero. Prevents income leakage by giving every dollar a job before the month begins.",
    category: "framework",
    methodology: "percentage",
    icon: "Target",
    color: "#0284c7",
    tags: ["Intentional", "Disciplined", "YNAB-Style"],
    period: "monthly",
    isSystem: true,
    allocations: [
      {
        categoryName: "Fixed Essentials",
        group: "Needs",
        percentage: 45,
        suggestedColor: "#0284c7",
        suggestedIcon: "ShieldCheck",
        alertThreshold: 90,
        description: "Rent, insurance, core utilities, and standard debt obligations.",
      },
      {
        categoryName: "Variable Day-to-Day",
        group: "Needs",
        percentage: 20,
        suggestedColor: "#10b981",
        suggestedIcon: "ShoppingBag",
        alertThreshold: 80,
        description: "Groceries, fuel, essential personal care, and medicine.",
      },
      {
        categoryName: "Discretionary & Dining",
        group: "Wants",
        percentage: 15,
        suggestedColor: "#f59e0b",
        suggestedIcon: "Coffee",
        alertThreshold: 80,
        description: "Social meals, entertainment, and personal fun spending.",
      },
      {
        categoryName: "Sinking Funds",
        group: "Savings",
        percentage: 10,
        suggestedColor: "#8b5cf6",
        suggestedIcon: "Calendar",
        alertThreshold: 100,
        description: "Anticipated future expenses: annual insurance, holidays, car repairs.",
      },
      {
        categoryName: "Investments & Wealth",
        group: "Savings",
        percentage: 10,
        suggestedColor: "#14b8a6",
        suggestedIcon: "TrendingUp",
        alertThreshold: 100,
        description: "Long-term index funds, stocks, retirement accounts.",
      },
    ],
    rulesSummary: [
      "Total budgeted allocations must equal 100% of expected monthly inflow.",
      "If you overspend in one category, move money from another category to balance it.",
      "Review weekly and reconcile unexpected cash movements immediately.",
    ],
    createdAt: new Date("2026-01-01"),
    updatedAt: new Date("2026-01-01"),
  },
  {
    _id: "freelancer",
    userId: null,
    organizationId: null,
    name: "Freelancer / Variable Income",
    tagline: "Stabilize erratic earnings with tax & buffer reserves",
    description:
      "Designed specifically for contractors, consultants, creators, and gig workers whose income fluctuates each month. Prioritizes tax withholding and builds a deep survival cushion.",
    category: "lifestyle",
    methodology: "percentage",
    icon: "Briefcase",
    color: "#f59e0b",
    tags: ["Freelance", "Variable Income", "Self-Employed"],
    period: "monthly",
    isSystem: true,
    allocations: [
      {
        categoryName: "Baseline Living Needs",
        group: "Needs",
        percentage: 40,
        suggestedColor: "#f59e0b",
        suggestedIcon: "Home",
        alertThreshold: 85,
        description: "Core survival floor: rent, groceries, and essential utilities.",
      },
      {
        categoryName: "Tax & Business Reserve",
        group: "Savings",
        percentage: 25,
        suggestedColor: "#dc2626",
        suggestedIcon: "FileText",
        alertThreshold: 100,
        description: "Self-employment taxes, GST/VAT, and professional software tools.",
      },
      {
        categoryName: "Cash Buffer & Emergency",
        group: "Savings",
        percentage: 20,
        suggestedColor: "#10b981",
        suggestedIcon: "ShieldAlert",
        alertThreshold: 100,
        description: "Rainy-day stabilization buffer for dry client months.",
      },
      {
        categoryName: "Personal Discretionary",
        group: "Wants",
        percentage: 15,
        suggestedColor: "#8b5cf6",
        suggestedIcon: "Sparkles",
        alertThreshold: 75,
        description: "Flexible lifestyle spending adjusted during high vs low earning months.",
      },
    ],
    rulesSummary: [
      "Always set aside 25% for taxes the moment any client invoice clears.",
      "Live on your minimum baseline floor and funnel surplus during peak months into your buffer.",
      "Never increase fixed lifestyle expenses during temporary revenue spikes.",
    ],
    createdAt: new Date("2026-01-01"),
    updatedAt: new Date("2026-01-01"),
  },
  {
    _id: "debt-payoff",
    userId: null,
    organizationId: null,
    name: "Aggressive Debt Payoff",
    tagline: "Crush high-interest liabilities with laser focus",
    description:
      "A high-intensity framework inspired by the Debt Snowball and Debt Avalanche strategies. Strips down discretionary spending to accelerate freedom from high-cost loans.",
    category: "goals",
    methodology: "percentage",
    icon: "TrendingDown",
    color: "#e11d48",
    tags: ["Debt-Free", "Snowball", "High-Intensity"],
    period: "monthly",
    isSystem: true,
    allocations: [
      {
        categoryName: "Housing & Utilities",
        group: "Needs",
        percentage: 40,
        suggestedColor: "#64748b",
        suggestedIcon: "Home",
        alertThreshold: 90,
        description: "Essential shelter and warmth.",
      },
      {
        categoryName: "Groceries & Basic Health",
        group: "Needs",
        percentage: 15,
        suggestedColor: "#10b981",
        suggestedIcon: "HeartPulse",
        alertThreshold: 80,
        description: "Wholesome food and healthcare needs.",
      },
      {
        categoryName: "Extreme Discretionary Trim",
        group: "Wants",
        percentage: 5,
        suggestedColor: "#f59e0b",
        suggestedIcon: "Coffee",
        alertThreshold: 70,
        description: "Absolute bare minimum allowance for sanity.",
      },
      {
        categoryName: "Emergency Starter Reserve",
        group: "Savings",
        percentage: 5,
        suggestedColor: "#0ea5e9",
        suggestedIcon: "ShieldCheck",
        alertThreshold: 100,
        description: "A small cash shield so minor emergencies don't force new borrowing.",
      },
      {
        categoryName: "Debt Acceleration Paydown",
        group: "Savings",
        percentage: 35,
        suggestedColor: "#e11d48",
        suggestedIcon: "Zap",
        alertThreshold: 100,
        description: "Aggressive principal prepayments targeting your highest APR debt first.",
      },
    ],
    rulesSummary: [
      "Cut dining out, subscriptions, and shopping to the bare minimum.",
      "Send all extra monthly surplus directly to your target loan.",
      "Once debt is cleared, reallocate that 35% directly to high-yield wealth building.",
    ],
    createdAt: new Date("2026-01-01"),
    updatedAt: new Date("2026-01-01"),
  },
  {
    _id: "family",
    userId: null,
    organizationId: null,
    name: "Family & Household",
    tagline: "Balanced living for households with dependents",
    description:
      "Structured for families managing mortgage/rent, groceries, childcare, schooling, healthcare, and family activities while steadily growing college and retirement reserves.",
    category: "lifestyle",
    methodology: "percentage",
    icon: "Users",
    color: "#3b82f6",
    tags: ["Family", "Household", "Dependents"],
    period: "monthly",
    isSystem: true,
    allocations: [
      {
        categoryName: "Housing & Mortgage",
        group: "Needs",
        percentage: 28,
        suggestedColor: "#3b82f6",
        suggestedIcon: "Home",
        alertThreshold: 85,
        description: "Family home mortgage, rent, property tax, and insurance.",
      },
      {
        categoryName: "Groceries & Household Goods",
        group: "Needs",
        percentage: 18,
        suggestedColor: "#10b981",
        suggestedIcon: "ShoppingCart",
        alertThreshold: 80,
        description: "Bulk family food shopping, cleaning supplies, and toiletries.",
      },
      {
        categoryName: "Childcare & Schooling",
        group: "Needs",
        percentage: 14,
        suggestedColor: "#8b5cf6",
        suggestedIcon: "GraduationCap",
        alertThreshold: 85,
        description: "Daycare, tuition, school supplies, sports, and after-school programs.",
      },
      {
        categoryName: "Health & Family Insurance",
        group: "Needs",
        percentage: 10,
        suggestedColor: "#ec4899",
        suggestedIcon: "ShieldPlus",
        alertThreshold: 90,
        description: "Medical insurance premiums, prescriptions, and dental care.",
      },
      {
        categoryName: "Utilities & Transit",
        group: "Needs",
        percentage: 10,
        suggestedColor: "#0ea5e9",
        suggestedIcon: "Car",
        alertThreshold: 85,
        description: "Family car fuel, maintenance, electricity, water, and broadband.",
      },
      {
        categoryName: "Family Fun & Outings",
        group: "Wants",
        percentage: 8,
        suggestedColor: "#f59e0b",
        suggestedIcon: "Smile",
        alertThreshold: 80,
        description: "Weekend outings, movies, family dining, and small celebrations.",
      },
      {
        categoryName: "Emergency & Future Growth",
        group: "Savings",
        percentage: 12,
        suggestedColor: "#14b8a6",
        suggestedIcon: "PiggyBank",
        alertThreshold: 100,
        description: "6-month emergency reserve and education funds.",
      },
    ],
    rulesSummary: [
      "Track bulk grocery runs and utility spikes during summer/winter months.",
      "Protect against family emergencies with an intact 6-month liquidity fund.",
      "Plan sinking funds 3–6 months ahead for seasonal school fees and holidays.",
    ],
    createdAt: new Date("2026-01-01"),
    updatedAt: new Date("2026-01-01"),
  },
  {
    _id: "student",
    userId: null,
    organizationId: null,
    name: "College Student / Young Adult",
    tagline: "Lean spending with a focus on education and social life",
    description:
      "A realistic, low-friction framework for students balancing tuition, dorm or room rent, meal plans, textbooks, and campus social activities on limited allowances or part-time earnings.",
    category: "lifestyle",
    methodology: "percentage",
    icon: "GraduationCap",
    color: "#a855f7",
    tags: ["Student", "Young Adult", "Entry-Level"],
    period: "monthly",
    isSystem: true,
    allocations: [
      {
        categoryName: "Rent & Housing",
        group: "Needs",
        percentage: 40,
        suggestedColor: "#a855f7",
        suggestedIcon: "Home",
        alertThreshold: 90,
        description: "Dorm fees, shared apartment rent, or room sublet.",
      },
      {
        categoryName: "Groceries & Food",
        group: "Needs",
        percentage: 20,
        suggestedColor: "#10b981",
        suggestedIcon: "ShoppingBag",
        alertThreshold: 80,
        description: "Meal plan top-ups, grocery runs, and basic sustenance.",
      },
      {
        categoryName: "Textbooks & Tech",
        group: "Needs",
        percentage: 10,
        suggestedColor: "#0ea5e9",
        suggestedIcon: "Laptop",
        alertThreshold: 85,
        description: "Course materials, stationery, software subscriptions, and printing.",
      },
      {
        categoryName: "Social & Entertainment",
        group: "Wants",
        percentage: 15,
        suggestedColor: "#f43f5e",
        suggestedIcon: "PartyPopper",
        alertThreshold: 80,
        description: "Campus events, parties, cafes, and streaming.",
      },
      {
        categoryName: "Campus Transit",
        group: "Needs",
        percentage: 10,
        suggestedColor: "#f59e0b",
        suggestedIcon: "Bike",
        alertThreshold: 80,
        description: "Metro/bus passes, bike upkeep, or rideshares.",
      },
      {
        categoryName: "Emergency Starter Fund",
        group: "Savings",
        percentage: 5,
        suggestedColor: "#14b8a6",
        suggestedIcon: "Coins",
        alertThreshold: 100,
        description: "Modest reserve for emergency travel or unexpected costs.",
      },
    ],
    rulesSummary: [
      "Avoid credit card debt for campus lifestyle or spring break expenses.",
      "Take full advantage of student discounts on tech, food, and transport.",
      "Cook with roommates to keep the grocery percentage low.",
    ],
    createdAt: new Date("2026-01-01"),
    updatedAt: new Date("2026-01-01"),
  },
  {
    _id: "digital-nomad",
    userId: null,
    organizationId: null,
    name: "Digital Nomad / Traveler",
    tagline: "Optimized for borderless living, travel, and co-working",
    description:
      "Crafted for remote workers and travelers whose biggest expenses are flexible accommodations, inter-city flights/trains, local cafes, and international nomad health insurance.",
    category: "lifestyle",
    methodology: "percentage",
    icon: "Compass",
    color: "#14b8a6",
    tags: ["Nomad", "Travel", "Remote Work"],
    period: "monthly",
    isSystem: true,
    allocations: [
      {
        categoryName: "Accommodations & Stays",
        group: "Needs",
        percentage: 35,
        suggestedColor: "#14b8a6",
        suggestedIcon: "Building",
        alertThreshold: 85,
        description: "Monthly Airbnbs, coliving spaces, hotels, and guesthouses.",
      },
      {
        categoryName: "Dining & Local Food",
        group: "Wants",
        percentage: 20,
        suggestedColor: "#f59e0b",
        suggestedIcon: "Utensils",
        alertThreshold: 80,
        description: "Exploring local street food, cafes, and restaurants.",
      },
      {
        categoryName: "Flights & Regional Transit",
        group: "Needs",
        percentage: 15,
        suggestedColor: "#0ea5e9",
        suggestedIcon: "Plane",
        alertThreshold: 85,
        description: "Flights, trains, visa fees, and luggage transfers.",
      },
      {
        categoryName: "Co-working & Connectivity",
        group: "Needs",
        percentage: 10,
        suggestedColor: "#6366f1",
        suggestedIcon: "Wifi",
        alertThreshold: 90,
        description: "Hotdesks, eSIMs, local SIM cards, and cloud VPNs.",
      },
      {
        categoryName: "Experiences & Excursions",
        group: "Wants",
        percentage: 10,
        suggestedColor: "#ec4899",
        suggestedIcon: "Camera",
        alertThreshold: 80,
        description: "Scuba diving, guided tours, museums, and weekend trips.",
      },
      {
        categoryName: "Nomad Health & Safety Buffer",
        group: "Savings",
        percentage: 10,
        suggestedColor: "#10b981",
        suggestedIcon: "ShieldAlert",
        alertThreshold: 100,
        description: "Travel health insurance and flight change contingencies.",
      },
    ],
    rulesSummary: [
      "Book 30+ day stays for Airbnb or coliving discounts to keep housing under 35%.",
      "Always maintain high-speed connectivity as a non-negotiable business need.",
      "Never travel without international health coverage and emergency flight funds.",
    ],
    createdAt: new Date("2026-01-01"),
    updatedAt: new Date("2026-01-01"),
  },
  {
    _id: "minimalist",
    userId: null,
    organizationId: null,
    name: "Minimalist / High-Savings FI-RE",
    tagline: "Radical efficiency to achieve Financial Independence early",
    description:
      "A high-savings framework for advocates of the FI-RE (Financial Independence, Retire Early) movement. Caps lifestyle costs to channel 50% of income into income-generating assets.",
    category: "goals",
    methodology: "percentage",
    icon: "Minimize2",
    color: "#10b981",
    tags: ["FI-RE", "Minimalist", "High-Savings"],
    period: "monthly",
    isSystem: true,
    allocations: [
      {
        categoryName: "Modest Housing",
        group: "Needs",
        percentage: 25,
        suggestedColor: "#64748b",
        suggestedIcon: "Home",
        alertThreshold: 90,
        description: "Right-sized, affordable living space without lifestyle creep.",
      },
      {
        categoryName: "Wholesome Food & Utilities",
        group: "Needs",
        percentage: 15,
        suggestedColor: "#0ea5e9",
        suggestedIcon: "ShoppingBag",
        alertThreshold: 80,
        description: "Home-cooked meals, essential bills, and modest transit.",
      },
      {
        categoryName: "Intentional Living",
        group: "Wants",
        percentage: 10,
        suggestedColor: "#8b5cf6",
        suggestedIcon: "Sparkles",
        alertThreshold: 75,
        description: "Curated experiences and purchases that bring high personal joy.",
      },
      {
        categoryName: "High-Velocity Investments",
        group: "Savings",
        percentage: 50,
        suggestedColor: "#10b981",
        suggestedIcon: "TrendingUp",
        alertThreshold: 100,
        description: "Aggressive low-cost index funds, equities, and real estate investments.",
      },
    ],
    rulesSummary: [
      "Maintain a 50%+ savings rate to dramatically compress your time to retirement.",
      "Resist lifestyle inflation when your income grows; invest 100% of raises.",
      "Prioritize financial freedom and time autonomy over material possessions.",
    ],
    createdAt: new Date("2026-01-01"),
    updatedAt: new Date("2026-01-01"),
  },
]
